# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
 adapter: postgresql

development:
 <<: *default
 database: gcamp_development

test:
 <<: *default
 database: gcamp_test

 test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres
